export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const GET_POST_TO_UPDATE = 'GET_POST_TO_UPDATE'
export const GET_POST_TO_UPDATE_ERROR = 'GET_POST_TO_UPDATE_ERROR'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'